[tool.poetry]
name = "ebpforgery"
version = "0.1.0"
description = "Ippers in ebpf"
authors = ["Jay", "Francois"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
